export const DIFFICULTY_LEVELS = {
  1: { level: 1, label: 'Easy', color: 'emerald', bg: 'bg-emerald-50', text: 'text-emerald-700', border: 'border-emerald-200', stars: '★☆☆☆☆' },
  2: { level: 2, label: 'Low', color: 'blue', bg: 'bg-blue-50', text: 'text-blue-700', border: 'border-blue-200', stars: '★★☆☆☆' },
  3: { level: 3, label: 'Medium', color: 'amber', bg: 'bg-amber-50', text: 'text-amber-700', border: 'border-amber-200', stars: '★★★☆☆' },
  4: { level: 4, label: 'Hard', color: 'orange', bg: 'bg-orange-50', text: 'text-orange-700', border: 'border-orange-200', stars: '★★★★☆' },
  5: { level: 5, label: 'Very Hard', color: 'rose', bg: 'bg-rose-50', text: 'text-rose-700', border: 'border-rose-200', stars: '★★★★★' },
};

export const DEFAULT_FLATMATES = [
  {
    id: 'f-soham',
    name: 'Soham',
    avatar: '👨‍💻',
    color: '#6366f1',
    role: 'Flatmate',
    email: 'soham@flatmates.local',
    onLeave: false,
    joinedDate: '2026-09-01',
    totalCompleted: 0,
    totalDifficultyPoints: 0,
  },
  {
    id: 'f-pranay',
    name: 'Pranay',
    avatar: '🧑‍🔬',
    color: '#06b6d4',
    role: 'Flatmate',
    email: 'pranay@flatmates.local',
    onLeave: false,
    joinedDate: '2026-09-01',
    totalCompleted: 0,
    totalDifficultyPoints: 0,
  },
  {
    id: 'f-pranav',
    name: 'Pranav',
    avatar: '🧑‍🎨',
    color: '#f59e0b',
    role: 'Flatmate',
    email: 'pranav@flatmates.local',
    onLeave: false,
    joinedDate: '2026-09-01',
    totalCompleted: 0,
    totalDifficultyPoints: 0,
  },
  {
    id: 'f-himanshu',
    name: 'Himanshu',
    avatar: '🧑‍🚀',
    color: '#8b5cf6',
    role: 'Flatmate',
    email: 'himanshu@flatmates.local',
    onLeave: false,
    joinedDate: '2026-09-01',
    totalCompleted: 0,
    totalDifficultyPoints: 0,
  },
];

export const DEFAULT_CHORES = [
  {
    id: 'c-cleaning',
    title: 'Cleaning',
    difficulty: 3,
    icon: 'Sparkles',
    category: 'Housekeeping',
    description: 'Vacuum living room, mop hallway floors, and dust common surfaces.',
    estimatedMinutes: 60,
  },
  {
    id: 'c-washing-dishes',
    title: 'Washing Dishes',
    difficulty: 2,
    icon: 'Utensils',
    category: 'Kitchen',
    description: 'Clear kitchen sink, wash pots/pans, wipe counters, and empty dishwasher.',
    estimatedMinutes: 40,
  },
  {
    id: 'c-garbage',
    title: 'Garbage',
    difficulty: 1,
    icon: 'Trash2',
    category: 'Disposal',
    description: 'Segregate dry & wet waste, empty common bins, and take bags out.',
    estimatedMinutes: 20,
  },
  {
    id: 'c-cooking',
    title: 'Cooking',
    difficulty: 4,
    icon: 'ChefHat',
    category: 'Kitchen',
    description: 'Plan meal, prepare dinner for all flatmates, and clean prep station.',
    estimatedMinutes: 90,
  },
];
